services:
  whisper-transcribe:
    build: .
    container_name: whisper-transcribe
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - API_PORT=${API_PORT:-8000}
      - AUDIO_DIR=${AUDIO_DIR:-./audio}
      - MODEL_SIZE=${MODEL_SIZE:-tiny}
      - PYTHONPATH=/app/whisper-20250625
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ${AUDIO_DIR:-./audio}:/app/audio:ro
      - ./whisper-20250625:/app/whisper-20250625:ro
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]